//PUT http://localhost:3001/api/persons/4
PUT https://phonebook-api-backend-production-1267.up.railway.app/api/persons/64f6c071159e9a1bef0a3c42
content-type: application/json

{
    "name": "Juanda",
    "number": "3137219437"
}