//PUT http://localhost:3001/api/persons/4
PUT https://phonebook-api-backend-production-1267.up.railway.app/api/persons/64f9370d26fdecf145229028
content-type: application/json

{
    "name": "Juanda",
    "number": "3137219437"
}